### ISSUE TITLE
grep issue on macOS 10.14.6 (Mojave)

### ISSUE THREAD

**Issue by myugan** [Screetsec/Sudomy#1]
Tools is installed but error when running on grep command. 

``` 
grep --version
grep (BSD grep) 2.5.1-FreeBSD
```

This is the error when i running enumeration `./sudomy -d hackerone.com`.

![image](https://user-images.githubusercontent.com/20453528/63633095-9203c900-c66c-11e9-911e-befa9eed88f4.png)

**Comment by Screetsec** [comment]
Try update your grep version 

``` bash
brew install grep
export PATH="/usr/local/opt/grep/libexec/gnubin:$PATH"
```
