### ISSUE TITLE
Error: require jq but it's is not installed. Aborting.

### ISSUE THREAD

**Issue by 7h3pr0xy** [Screetsec/Sudomy#10]
Help me out

**Comment by Screetsec** [comment]
Sudomy requires jq to run and pars. For more information, Download and install jq here


```bash
# Linux
apt-get install jq nmap phantomjs

# Mac
brew cask install phantomjs
brew install jq nmap
```

**Comment by Mrjavaci** [comment]
> Sudomy requires jq to run and pars. For more information, Download and install jq here
> 
> ```shell
> # Linux
> apt-get install jq nmap phantomjs
> 
> # Mac
> brew cask install phantomjs
> brew install jq nmap
> ```

```
# Mac
brew install phantomjs --cask
brew install jq nmap
```
