### ISSUE TITLE
Dnsdumpster jq: error

### ISSUE THREAD

**Issue by ZeroDot1** [Screetsec/Sudomy#13]
[*] Load target domain: domain.com 
    - starting scanning @ 2019-10-17 16:16:44 

[+] Running & Checking source to be used  
---------------------------------------------

    ⍥  Shodan				[ ✔ ]
    ⍥  Webarchive			[ ✔ ]
    ⍥  Virustotal			[ ✔ ]
    ⍥  Certsh				[ ✔ ]
    ⍥  Censys				[ ✕ ]
    ⍥  Binaryedge			[ ✕ ]
    ⍥  Entrust				[ ✔ ]
    ⍥  Certspotter			[ ✔ ]
    ⍥  Bufferover			[ ✔ ]
    ⍥  Threatcrowd			[ ✔ ]
    ⍥  Securitytrails			[ ✔ ]
    ⍥  Riddler				[ ✔ ]
    ⍥  Hackertarget			[ ✔ ]
    ⍥  Threatminer			[ ✔ ]
    ⍥  Dnsdumpster			[ ✔ ]
jq: error (at <stdin>:0): Cannot iterate over null (null)
    ⍥  Findsubdomain			[ ✔ ]

**Comment by Screetsec** [comment]
DNSDumpster update regex  for retrieving csrfMiddlewaretoken values

**Comment by ZeroDot1** [comment]
Thanks for the update.
