### ISSUE TITLE
Invalid subdomains in the results.

### ISSUE THREAD

**Issue by ZeroDot1** [Screetsec/Sudomy#16]
Hi @Screetsec,

Sometimes when I search for subdomains I get incorrect URLs in the results.
Here are some examples:

```
0 bpool.id.
10 dc-3ba5129c147c.saltpool.net.
10 gnark-mining.com.
10 mail.miningcoins.ca.
5 post.blockhunter.info.
```

I hope the information is useful for you to fix the bug.

**Comment by Screetsec** [comment]
that was relations URL from web archive, but I will try to increase the accuracy in regex output
