### ISSUE TITLE
error while checking domain

### ISSUE THREAD

**Issue by totoroha** [Screetsec/Sudomy#33]
Dear Team,
I got this error while checking my test domain. Would you please tell me how to fix it? I'm using Sudomy on my mac OS.

./sudomy: line 374: wget: command not found
usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]
	[-e pattern] [-f file] [--binary-files=value] [--color=when]
	[--context[=num]] [--directories=action] [--label] [--line-buffered]
	[--null] [pattern] [file ...]
cat: /Users/tester/Downloads/Sudomy/output/FRiddler.log: No such file or directory
rm: /Users/tester/Downloads/Sudomy/output/FRiddler.log: No such file or directory
Traceback (most recent call last):
  File "lib/censys/censys_subdomain_finder.py", line 3, in <module>
    import censys.certificates
ImportError: No module named censys.certificates
jq: error (at <stdin>:16): Cannot iterate over null (null)
jq: error (at <stdin>:0): Cannot iterate over null (null)
jq: error (at <stdin>:0): Cannot iterate over null (null)
    ⍥  Findsubdomain			[ ✔ ]
sed: 1: "/Users/tester/Down ...": extra characters at the end of q command
(23) Failed writing body
usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]
	[-e pattern] [-f file] [--binary-files=value] [--color=when]
	[--context[=num]] [--directories=action] [--label] [--line-buffered]
	[--null] [pattern] [file ...]
(23) Failed writing body

**Comment by Screetsec** [comment]
Instal this 

```brew cask install phantomjs 
brew install jq nmap go
brew install grep
export PATH="/usr/local/opt/grep/libexec/gnubin:$PATH"
```

For detail check the fix issue in here : https://github.com/Screetsec/Sudomy/issues/1 

Or you can run this tools using docker :))
