### ISSUE TITLE
Reduce Fly.io false positives in subdomain takeover

### ISSUE THREAD

**Issue by darshkpatel** [Screetsec/Sudomy#38]
The check for Fly.io subdomain takeover is simply 
checking for `"404 Not Found"` , which is a really common string, and thus has a lot of false positives.

**Comment by Screetsec** [comment]
Thank's for suggestion, any referenece ? 

For method followed in this source : https://github.com/EdOverflow/can-i-take-over-xyz

**Comment by darshkpatel** [comment]
Couldn't find any references, but I can setup an experiment to find some other string to look for

**Comment by subhash0x** [comment]
is there any way to confirm Fly.io subdomain takeover?

**Comment by Screetsec** [comment]
Nicee ! @darshkpatel

**Comment by darshkpatel** [comment]
Fly.io Subdomain takeover seems to be fixed since they added a verification before adding custom domains. 
[#132 on can-i-take-over-xyz](https://github.com/EdOverflow/can-i-take-over-xyz/issues/132#issuecomment-614070737)

PR: #44
