### ISSUE TITLE
Threatminer    parse error: Invalid numeric literal at line 1, column 7

### ISSUE THREAD

**Issue by briefcasehi** [Screetsec/Sudomy#46]
Hi

```
Threatminer    parse error: Invalid numeric literal at line 1, column 7
```
Please fix it!

Thanks!

**Comment by presianbg** [comment]
Hi
same with using the docker image:
![image](https://user-images.githubusercontent.com/2163486/80914379-d85d0c00-8d53-11ea-8b62-e5f72186b0bf.png)

**Comment by Screetsec** [comment]
Fixing done : Update to new version of sudomy 1.1.5#dev

**Comment by rudSarkar** [comment]
@screetsec started facing this issue recently in macOS iTerm version 3.4.14.

**Comment by r3l1c7** [comment]
issue is not resolved

**Comment by RAF-87** [comment]
Having this issue too.

**Comment by rudra0x01** [comment]
> @screetsec Having this issue too.

It's not a problem because the project is working fine

**Comment by r3l1c7** [comment]
> > @screetsec Having this issue too.
> 
> It's not a problem because the project is working fine

 It's obviously a problem for some of us, we aren't posting about it for no reason.

**Comment by rudSarkar** [comment]
> > > @screetsec Having this issue too.
> > 
> > 
> > It's not a problem because the project is working fine
> 
> It's obviously a problem for some of us, we aren't posting about it for no reason.

Can you specify what kind of problem it is causing while running the scan, aren't you getting results? I faced the same issue but I found that it's nothing but a debug error.

If you facing some code breaking then comment it.
