### ISSUE TITLE
Unable to run Sudomy in Docker

### ISSUE THREAD

**Issue by soareswallace** [Screetsec/Sudomy#58]
I'm getting this error when trying to pull from Docker Hub

```
⋊> ~ docker pull screetsec/sudomy:v1.1.6-dev                                                          
Error response from daemon: manifest for screetsec/sudomy:v1.1.6-dev not found: manifest unknown: manifest unknown
```
 Anyone has figure out how to solve?

**Comment by myugan** [comment]
You can see available tags in here https://hub.docker.com/r/screetsec/sudomy/tags, I think the `README.md` have wrong tags about docker tags.

Thankyou

**Comment by soareswallace** [comment]
It’s true. I will open a PR for that.
