### ISSUE TITLE
Unable to pass API keys when using docker container

### ISSUE THREAD

**Issue by soareswallace** [Screetsec/Sudomy#65]
I'm getting this message

```
Invalid: Unknown option -e
```

**Comment by myugan** [comment]
can you send the full command? i think you miss something when running with docker image.

**Comment by soareswallace** [comment]
I don't have my PC now, but I believe I use this one

`docker run -v "${PWD}/output:/usr/lib/sudomy/output" -e "SHODAN_API=xxxx" -e "VIRUSTOTAL=xxxx" -it --rm screetsec/sudomy:v1.1.7 [argument]`

Is the one in the documentation. Which one did you use?

**Comment by soareswallace** [comment]
Went trough my terminal history. I used this one:

`docker run -it --rm screetsec/sudomy:v1.1.7 -d <domain> -a -e "SHODAN_API=<api_key>"`

**Comment by soareswallace** [comment]
Yeap, I believe I use the command incorrectly. Running on a Mac I was unable to pass this argument `-v "${PWD}/output:/usr/lib/sudomy/output"`. I started looking how to run and got this one. `-e` is an option from docker, not from Sudomy. Thats why I got `Unknown option`.

How can I pass this argument `"${PWD}/output:/usr/lib/sudomy/output"` on a Mac? Do you know?
