### ISSUE TITLE
how to fix package 'phantomjs' has no installation candidate

### ISSUE THREAD

**Issue by rahmatdani** [Screetsec/Sudomy#67]
i using kali linux 2020.2, how to fix this problem

**Comment by Screetsec** [comment]
Please update your repo's and try to :

- apt-get clean
- apt-get update && apt-get upgrade 

Then try to install again

**Comment by rahmatdani** [comment]
waduh bang edo maland sang panutanque.

sudah sya lakukan, tpi masih error yang sama
![img](https://imgur.com/SnoyAMQ.png)

jadi yang sya lakukan, 
apt-get install jq
apt-get install nmap
install phantomjs dengan tutorial ini https://tecadmin*net/install-phantomjs-on-ubuntu/ tpi dapat error seperti ini setelah menjankannya
![img](https://imgur.com/SKbfqm1.png)
apt-get install npm

kemudian lanjut 
npm i -g wappalyzer wscat
![img](https://imgur.com/KrxFvss.png)

kemudian sya jalankan dengan perintah sudo ./sudomy --all -d hackerone.com --html
beberapa error yang sya dapatkan
![img](https://imgur.com/1F4Iegi.png)

![img](https://imgur.com/j8rCOZs.png)

![img](https://imgur.com/qntah0R.png)

**Comment by Screetsec** [comment]
For phantomjs try to reinstall, it is already installed but some package is not working and jq error problem, I will fix my regex and parsing.

**Comment by restuhaqza** [comment]
phantomjs was build from NodeJS. if you can't install phantomjs using aptitude. maybe you can try to install officially from Node Package Manager.  for the steps is like this : 
1. Install Node Version Manager
```
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
```
2. Install Node >= v8
```
nvm install node
```
3. Getting PhantomJS and install as globally
```
npm install -g phantomjs
```

If your computers were installed for nodejs. I think you can move to steps 3 instantly. but I suggest you using node from NVM.

Good luck,

**Comment by sitakom** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/16697588/102161557-20cbd300-3eba-11eb-95d5-7b815b71c893.png)

mungkin bisa sebagai tambahan problem solving nya.

posisi saya install phantomjs di Kali-Linux-2020.3-vmware dan error nya sama seperti yang ada di thread di atas.

Semoga Berhasil.
