### ISSUE TITLE
cf-check missing

### ISSUE THREAD

**Issue by ShinTakata** [Screetsec/Sudomy#68]
how to resolve this issue? 

 - Warning: require cf-check but it's is not installed.Trying to setup pkg_cf-check
cp: missing destination file operand after '/usr/local/bin/'

**Comment by Screetsec** [comment]
What distro do you use ? 

For ezy solve this issue, run this
```
cp lib/bin/cf-check /usr/bin 

```
or
```

cp lib/bin/cf-check /usr/local/bin/
```

**Comment by ShinTakata** [comment]
i use the latest kali linux 2020
