### ISSUE TITLE
Cant install Chromium package while installation

### ISSUE THREAD

**Issue by kratos-is-alive** [Screetsec/Sudomy#69]
##Cant install chromium packages .
### apt-get install jq nmap phantomjs npm chromium parallel
It is giving me this error 

Package chromium is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
 chromium-bsu:i386 chromium-bsu
E: Package 'chromium' has no installation candidate

Please help me.

**Comment by Screetsec** [comment]
apt-get clean; apt-get update 

then try to install again

**Comment by kratos-is-alive** [comment]
[⍥] Perfoming Sud⍥my scans  
    - Warning: require dnsprobe but it's is not installed.Trying to setup pkg_httpx 
cp: cannot create regular file '/usr/local/bin/dnsprobe': Permission denied
    - Warning: require webanalyze but it's is not installed.Trying to setup pkg_webanalyze 
cp: cannot create regular file '/usr/local/bin/webanalyze': Permission denied
    - Warning: require cf-check but it's is not installed.Trying to setup pkg_cf-check 
cp: missing destination file operand after '/usr/local/bin/'
Try 'cp --help' for more information.
    - Warning: require gowitness but it's is not installed.Trying to setup pkg_gowitness 
cp: cannot create regular file '/usr/local/bin/gowitness': Permission denied
    - Warning: require subjack but it's is not installed.Trying to setup pkg_subjack 
cp: cannot create regular file '/usr/local/bin/subjack': Permission denied

Should i need to install these tools by myself?

**Comment by kratos-is-alive** [comment]
# Also These few errors

loadDep:puppeteer → resol ▌ ╢█████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
/usr/local/bin/wappalyzer -> /usr/local/lib/node_modules/wappalyzer/cli.js
/usr/local/bin/wscat -> /usr/local/lib/node_modules/wscat/bin/wscat
/usr/local/lib
├── wappalyzer@6.0.12 
└─┬ wscat@4.0.1 
  ├── UNMET PEER DEPENDENCY bufferutil@^4.0.1
  └── UNMET PEER DEPENDENCY utf-8-validate@^5.0.2

npm WARN ws@7.3.0 requires a peer of bufferutil@^4.0.1 but none was installed.
npm WARN ws@7.3.0 requires a peer of utf-8-validate@^5.0.2 but none was installed.

while running the command "npm i -g wappalyzer wscat"

**Comment by pdelteil** [comment]
> ##Cant install chromium packages .
> ### After running this below command in my ubuntu18.4
> ### apt-get install jq nmap phantomjs npm chromium parallel
> 
> It is giving me this error
> 
> Package chromium is not available, but is referred to by another package.
> This may mean that the package is missing, has been obsoleted, or
> is only available from another source
> However the following packages replace it:
> chromium-bsu:i386 chromium-bsu
> E: Package 'chromium' has no installation candidate
> 
> Please help me.

The package name is chromium-browser in Ubuntu 18/20
