### ISSUE TITLE
Screenshots in Docker

### ISSUE THREAD

**Issue by allahcurse** [Screetsec/Sudomy#70]
When using Sudomy from docker, this screenshot feature fails since there is no chrome.

`Unable to locate a valid installation of Chrome to use. gowitness needs at least Chrome/Chrome Canary v60+. Either install Google Chrome or try specifying a valid location with the --chrome-path flag`

How would I go about fixing that?

**Comment by myugan** [comment]
Please try our new image with tag version `v1.1.9-dev`
