### ISSUE TITLE
facing this issue 

### ISSUE THREAD

**Issue by prosecurity** [Screetsec/Sudomy#71]
[⍥] Perfoming Sud⍥my scans  
    - Warning: require cf-check but it's is not installed.Trying to setup pkg_cf-check 
cp: missing destination file operand after '/usr/local/bin/'
Try 'cp --help' for more information.

**Comment by prosecurity** [comment]
note that i already run go get -u url/cf-check and still facing this issue

**Comment by Screetsec** [comment]
https://github.com/Screetsec/Sudomy/issues/68
