### ISSUE TITLE
Error while using tool

### ISSUE THREAD

**Issue by R0X4R** [Screetsec/Sudomy#72]
I get these issues while using the tool.

``
[⍥] Perfoming Sud⍥my scans  
    - Warning: require cf-check but it's is not installed.Trying to setup pkg_cf-check 
cp: missing destination file operand after '/usr/local/bin/'
Try 'cp --help' for more information.
``

I used pip install censys it says requirements satisfied.

+ ``
Traceback (most recent call last):
  File "lib/censys/censys_subdomain_finder.py", line 3, in <module>
    import censys.certificates
ImportError: No module named censys.certificates
``

+ ``
/root/tools/subdomain-enum/Sudomy/plugin/exec_takeover: line 55: parallel: command not found
``

**Comment by pdelteil** [comment]
For the first one you need to install cf-check manually:
`go get -u github.com/dwisiswant0/cf-check`

And then copy the binary to /usr/local/bin:

`sudo cp cf-check /usr/local/bin`
