### ISSUE TITLE
Getting npm error

### ISSUE THREAD

**Issue by welltest** [Screetsec/Sudomy#73]
npm i -g wappalyzer wscat

![2020-09-06 19_33_24-VPS](https://user-images.githubusercontent.com/7748482/92327554-1b1f4f80-f078-11ea-9fb1-68970db01e86.png)

root@kali:~# apt-get install npm
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libnode64 : Conflicts: nodejs-legacy
 nodejs : Conflicts: npm
E: Unable to correct problems, you have held broken packages.

**Comment by pdelteil** [comment]
I'm also having a lot of issues. 

To solve that problem you need to: 

`sudo apt-get install nodejs-legacy`
