### ISSUE TITLE
two problem  No module named censys.certificates and (23) Failed writing body

### ISSUE THREAD

**Issue by ringawy** [Screetsec/Sudomy#75]
Traceback (most recent call last):
  File "lib/censys/censys_subdomain_finder.py", line 3, in <module>
    import censys.certificates
ImportError: No module named censys.certificates
    ⍥  Findsubdomain                    [ ✔ ]
jq: error (at <stdin>:0): Cannot iterate over null (null)
parse error: Invalid numeric literal at line 1, column 109
    ⍥  Entrust                          [ ✕ ]
    ⍥  CommonwCrawl                     [ ✔ ]
(23) Failed writing body
(23) Failed writing body
(23) Failed writing body

**Comment by Screetsec** [comment]
Check here https://github.com/Screetsec/Sudomy/issues/74
