### ISSUE TITLE
Error: unknown flag: --source

### ISSUE THREAD

**Issue by welltest** [Screetsec/Sudomy#79]
Getting an error for gowitness 

Error: unknown flag: --source

![2020-10-13 23_18_20-128 199 59 13 - Remote Desktop Connection](https://user-images.githubusercontent.com/7748482/95896901-844a5f00-0daa-11eb-8e2b-495a3854386e.png)

**Comment by Screetsec** [comment]
What distro do you use and what the version of gowitness?
What command do you run?

Sudomy using version gowitness = v1.3.3,  you can copy the binary into  your local system /usr/bin/, usr/local/bin/ or on your $GOPATH.

```bash
cp lib/bin/cf-check /usr/bin 
```

Alternative methode to screenshots use this argument:
```bash
./sudomy -d bugcrowd.com -sS webscreenshot
```

**Comment by welltest** [comment]
I am using latest Gowitness and sudomy

Now tgtting an error "Error: unknown flag: --log-level" after changes /exec_gowitness line 20 as you told abbove.

![2020-10-14 17_07_55-VPS](https://user-images.githubusercontent.com/7748482/95983859-f4ef8b00-0e3f-11eb-84d7-7f3d52b15347.png)

**Comment by Screetsec** [comment]
Replace lines 20 to this and save it
```
${_GOWITNESS} file -f  ${OUT}/${DATE_LOG}/${DOMAIN}/${RESULT_HTTPROBE} --disable-logging -P  ${OUT}/${DATE_LOG}/${DOMAIN}/screenshots/ --db-path ${OUT}/${DATE_LOG}/${DOMAIN}/screenshots/gowitness.sqlite3
```
I've tried it and working on gowitness version 2.1.2

**Comment by welltest** [comment]
@Screetsec I did the same but still getting an error.

I am using this..
sudomy -d example.com  -dP -eP -rS -cF -pS -tO -gW --httpx --dnsprobe  -aI webanalyze --slack -sS

**Comment by welltest** [comment]
Error: unknown flag: --log-level 

this error due to line 24

**Comment by Screetsec** [comment]
Have you replaced the string on line 20?

**Comment by welltest** [comment]
> 
> 
> Have you replaced the string on line 20?

Yes I added

**Comment by Screetsec** [comment]
In this code,  we haven't pit the --log-level arugment, please pay attention to the code you changed
```
${_GOWITNESS} file -f  ${OUT}/${DATE_LOG}/${DOMAIN}/${RESULT_HTTPROBE} --disable-logging -P  ${OUT}/${DATE_LOG}/${DOMAIN}/screenshots/ --db-path ${OUT}/${DATE_LOG}/${DOMAIN}/screenshots/gowitness.sqlite3
```

**Comment by welltest** [comment]
> 
> 
> In this code, we haven't pit the --log-level arugment, please pay attention to the code you changed
> 
> ```
> ${_GOWITNESS} file -f  ${OUT}/${DATE_LOG}/${DOMAIN}/${RESULT_HTTPROBE} --disable-logging -P  ${OUT}/${DATE_LOG}/${DOMAIN}/screenshots/ --db-path ${OUT}/${DATE_LOG}/${DOMAIN}/screenshots/gowitness.sqlite3
> ```

I changed as to suggest, but --log-level argument used in **line 24**, please check

**Comment by Screetsec** [comment]
Ohh you are right,  I didn't notice it. You can delete it from line 22-25

**Comment by Screetsec** [comment]
For Fix this issues 

Downgrade Gowitness to version 1.1.3 /  Copy the binary into your local system /usr/bin/, usr/local/bin/ or on your $GOPATH. ```(cp lib/bin/gowitness /usr/bin)```

If you want use the latest gowitness versions

Edit the following scripts on https://github.com/Screetsec/Sudomy/blob/master/plugin/exec_gowitness line 20 to this:

 ```bash
${_GOWITNESS} file -f  ${OUT}/${DATE_LOG}/${DOMAIN}/${RESULT_HTTPROBE} --disable-logging -P  ${OUT}/${DATE_LOG}/${DOMAIN}/screenshots/ --db-path ${OUT}/${DATE_LOG}/${DOMAIN}/screenshots/gowitness.sqlite3
````

Then disable/delete the code from line 22-25
```
## Reports
#pushd ${OUT}/${DATE_LOG}/${DOMAIN}/screenshots/ > /dev/null
#${_GOWITNESS} report generate --log-level fatal 
#popd > /dev/null

```

**Comment by welltest** [comment]
@Screetsec Thanks, now working fine..
