### ISSUE TITLE
error using sudomy 

### ISSUE THREAD

**Issue by rijinrij** [Screetsec/Sudomy#80]
/sudomy: line 358: /home/mrcyguru/Desktop/Find/script/Dns: No such file or directory
./sudomy: line 359: /home/mrcyguru/Desktop/Find/script/Dns: No such file or directory
./sudomy: line 360: /home/mrcyguru/Desktop/Find/script/Dns: No such file or directory
./sudomy: line 361: /home/mrcyguru/Desktop/Find/script/Dns: No such file or directory
./sudomy: line 362: /home/mrcyguru/Desktop/Find/script/Dns: No such file or directory
./sudomy: line 363: /home/mrcyguru/Desktop/Find/script/Dns: No such file or directory
./sudomy: line 364: /home/mrcyguru/Desktop/Find/script/Dns: No such file or directory
./sudomy: line 365: /home/mrcyguru/Desktop/Find/script/Dns: No such file or directory
./sudomy: line 366: /home/mrcyguru/Desktop/Find/script/Dns: No such file or directory
./sudomy: line 367: /home/mrcyguru/Desktop/Find/script/Dns: No such file or directory
./sudomy: line 368: /home/mrcyguru/Desktop/Find/script/Dns: No such file or directory
./sudomy: line 369: /home/mrcyguru/Desktop/Find/script/Dns: No such file or directory
./sudomy: line 370: /home/mrcyguru/Desktop/Find/script/Dns: No such file or directory
./sudomy: line 371: /home/mrcyguru/Desktop/Find/script/Dns: No such file or directory
./sudomy: line 372: /home/mrcyguru/Desktop/Find/script/Dns: No such file or directory
./sudomy: line 373: /home/mrcyguru/Desktop/Find/script/Dns: No such file or directory
./sudomy: line 374: /home/mrcyguru/Desktop/Find/script/Dns: No such file or directory
./sudomy: line 375: /home/mrcyguru/Desktop/Find/script/Dns: No such file or directory
./sudomy: line 376: /home/mrcyguru/Desktop/Find/script/Dns: No such file or directory
./sudomy: line 377: /home/mrcyguru/Desktop/Find/script/Dns: No such file or directory
 ___         _ _  _           
/ __|_  _ __| (_)(_)_ __ _  _ 
\__ \ || / _  / __ \  ' \ || |
|___/\_,_\__,_\____/_|_|_\_, |
                          |__/ v{1.1.9#dev} by @screetsec 
Sud⍥my - Fast Subdmain Enumeration and Analyzer      
	 http://github.com/screetsec/sudomy

[!] This tool is for educational purpose only.   
    Usage of sudomy for attacking targets without prior mutual consent is illegal   
    developers assume no liability and are not responsible for any misuse or damage cause by this program   

[⍥] Perfoming Sud⍥my scans  

[*] Load target domain: xxxxxxx.com  
    - starting scanning @ 2020-10-20 21:04:17 

[+] Running & Checking source to be used  
---------------------------------------------

./sudomy: line 620: SHODAN: command not found
./sudomy: line 620: WEBARCHIVE: command not found
./sudomy: line 620: DNSDUMPSTER: command not found
./sudomy: line 620: CERTSPOTTER: command not found
./sudomy: line 620: CERTSH: command not found
./sudomy: line 620: BINARYEDGE: command not found
./sudomy: line 620: CENSYS: command not found
./sudomy: line 620: VIRUSTOTAL: command not found
./sudomy: line 620: THREATMINER: command not found
./sudomy: line 620: BUFFEROVER: command not found
./sudomy: line 620: FINDSUBDOMAIN: command not found
./sudomy: line 620: THREATCROWD: command not found
./sudomy: line 620: SECURITY_TRAILS: command not found
./sudomy: line 620: ENTRUST: command not found
./sudomy: line 620: ALIENVAULT: command not found
./sudomy: line 620: RAPIDDNS: command not found
./sudomy: line 620: URLSCAN: command not found
./sudomy: line 620: RIDDLER: command not found
./sudomy: line 620: COMMONCRAWL: command not found
./sudomy: line 620: HACKERTARGET: command not found

[+] Get & Count subdomain total From source   
---------------------------------------------

[+] Parsing & Sorting list Domain 
---------------------------------------------

./sudomy: line 339: ${OUT}/${DATE_LOG}/${DOMAIN}/${RESULT_SUBDOMAIN}: ambiguous redirect
sed: can't read /home/mrcyguru/Desktop/Find/script/Dns: No such file or directory
sed: can't read &subdomain/Sudomy/output/*.log: No such file or directory
./sudomy: line 919: /home/mrcyguru/Desktop/Find/script/Dns: No such file or directory
./sudomy: line 920: exec_httprobe: command not found

[+] Sud⍥my has been sucessfully completed

**Comment by myugan** [comment]
Did you run the script with `sudo`?

**Comment by rijinrij** [comment]
yes

**Comment by Screetsec** [comment]
Please, gives detail information like operating systems, bash version and what command do you use
