### ISSUE TITLE
Issues with the exec_gowitness

### ISSUE THREAD

**Issue by comoodooo** [Screetsec/Sudomy#84]
Hi, 

Just want to start with saying thanks so much for the hard work integrating all these tools into one. Second I don't know if I have done anything but it seems that some flags are not working for me when calling gowitness. 

Error: unknown flag: --source

Error: unknown flag: --log-level

Could try editing the command myself but just wanted to see if anyone else is experiencing this.

**Comment by Screetsec** [comment]
Hi too !! Your Welcome, for this issue you can check here  #https://github.com/Screetsec/Sudomy/issues/79
