### ISSUE TITLE
gowitness error

### ISSUE THREAD

**Issue by pxng0lin** [Screetsec/Sudomy#87]
`[+] Web Screenshots: from domain list
---------------------------------------------

Error: unknown flag: --source
Usage:
  gowitness file [input] [flags]

Examples:
$ gowitness file -f ~/Desktop/urls
$ gowitness file -f urls.txt --threads 2
$ cat urls.txt | gowitness file -f -
$ gowitness file -f <( shuf domains ) --no-http

Flags:
  -f, --file string   file containing urls. use - for stdin
  -h, --help          help for file
      --no-http       do not prefix http:// where missing
      --no-https      do not prefix https:// where missing
  -t, --threads int   threads used to run (default 4)

Global Flags:
      --chrome-path string       path to chrome executable to use
  -D, --db-path string           destination for the gowitness database (default "gowitness.sqlite3")
      --debug                    enable debug logging
      --disable-db               disable all database operations
      --disable-logging          disable all logging
  -F, --fullpage                 take fullpage screenshots
  -p, --proxy string             http/socks5 proxy to use. Use format proto://address:port
  -X, --resolution-x int         screenshot resolution x (default 1440)
  -Y, --resolution-y int         screenshot resolution y (default 900)
  -P, --screenshot-path string   store path for screenshots (use . for pwd) (default "screenshots")
      --timeout int              preflight check timeout (default 10)
      --user-agent string        user agent string to use (default "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36")

unknown flag: --source
Error: unknown flag: --log-level
Usage:
  gowitness report [command]

Available Commands:
  list        List entries in the gowitness database in various formats
  serve       starts a web server to view screenshot reports

Flags:
  -h, --help   help for report

Global Flags:
      --chrome-path string       path to chrome executable to use
  -D, --db-path string           destination for the gowitness database (default "gowitness.sqlite3")
      --debug                    enable debug logging
      --disable-db               disable all database operations
      --disable-logging          disable all logging
  -F, --fullpage                 take fullpage screenshots
  -p, --proxy string             http/socks5 proxy to use. Use format proto://address:port
  -X, --resolution-x int         screenshot resolution x (default 1440)
  -Y, --resolution-y int         screenshot resolution y (default 900)
  -P, --screenshot-path string   store path for screenshots (use . for pwd) (default "screenshots")
      --timeout int              preflight check timeout (default 10)
      --user-agent string        user agent string to use (default "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36")

Use "gowitness report [command] --help" for more information about a command.

unknown flag: --log-level

    ⍥  Total                            [0]

`

I seem to be getting this error on a regular, any idea if this can be manually corrected somewhere, or will it need to be updated on a new version?

**Comment by Screetsec** [comment]
https://github.com/Screetsec/Sudomy/issues/79
