### ISSUE TITLE
Error running Sudomy on last Kali - Invalid numeric literal at line 1, column 10

### ISSUE THREAD

**Issue by Nexsus1985** [Screetsec/Sudomy#88]
Hi, 

I followed the installation instructions and I receive this error when I try to run the tool on the latest kali.

`Invalid numeric literal at line 1, column 10`
I guess that the error  related to "jq"

![Error](https://user-images.githubusercontent.com/12773387/104715630-769cd080-572f-11eb-83d2-05640565eae3.PNG)

**Comment by Screetsec** [comment]
It seems that the API you are using has been limit, try check & change your api key
