### ISSUE TITLE
Error: require GNU grep. Aborting in OSX Mojave 10.14.6

### ISSUE THREAD

**Issue by naufalardhani** [Screetsec/Sudomy#96]
when i've entered the command "./sudomy -d domain.com --all" an error will appear like this "Error: require GNU grep. Aborting".  even though GNU Grep has been installed, the error will still appear as above.

![Screen Shot 2021-05-05 at 17 39 15](https://user-images.githubusercontent.com/33175548/117129525-fd51e800-adc8-11eb-988e-be03972ac381.png)

**Comment by Screetsec** [comment]
https://github.com/Screetsec/Sudomy/issues/1

**Comment by Screetsec** [comment]
This duplicate to this issue https://github.com/Screetsec/Sudomy/issues/1

**Comment by naufalardhani** [comment]
solved by ```$ export PATH="/usr/local/opt/grep/libexec/gnubin:$PATH"``` Thanks @Screetsec!

![Screen Shot 2021-05-06 at 17 57 00](https://user-images.githubusercontent.com/33175548/117287634-c1845480-ae94-11eb-86ec-d03a0de554ef.png)
