### ISSUE TITLE
ModuleNotFoundError: No module named 'pyvis'

### ISSUE THREAD

**Issue by itsethack** [Screetsec/Sudomy#98]
Hi, I had got error when "Make Network Graphys" on "Generate Visualization for Virtual Host'. 
![Screenshot_2021-06-04_05-11-47](https://user-images.githubusercontent.com/65939746/120784137-c4a54b80-c4f9-11eb-8a6e-7c199f426e14.png)

The error shows when execute nGraph.py.
I tried to reinstall the pyvis (pip uninstall pyvis - then install again), but still error on there.

Any solutions?

Thanks in advance

**Comment by Screetsec** [comment]
You install pyvis on python3 try to python27 using pip2

**Comment by itsethack** [comment]
Well, I have already try to using pip2 as your suggest,
But I still got the same error.
![still-error-pyvis](https://user-images.githubusercontent.com/65939746/121150567-d8401180-c86d-11eb-9301-194289bd8823.png)

So, I check the script to call nGraph and know that its on plugin/exec_nGraph.
and when I check the script in exec_nGraph, 
nGraph run using python3
![sudomy-ngraph](https://user-images.githubusercontent.com/65939746/121151257-65836600-c86e-11eb-8de4-e850ea725f1b.png)

I try to edit it to use python2, but still got the same error as before..

Then, I try again to use pyvis on python3 by upgrade it 
`sudo pip install --upgrade pyvis`
![upgrade-pyvis](https://user-images.githubusercontent.com/65939746/121153444-4685d380-c870-11eb-96d4-3f3c65c8599e.png)
Luckily, it works and can run nGraph well.
![sudomy-success](https://user-images.githubusercontent.com/65939746/121162937-94063e80-c878-11eb-8ed6-00da97e3b161.png)

Well, I think that is the solution for it.
